DECLARE
PERCEN NUMBER(3);
BEGIN
DBMS_OUTPUT.PUT_LINE('ENTER PERCENTAGE:');
PERCEN := &PERCEN;
IF PERCEN >= 90 THEN DBMS_OUTPUT.PUT_LINE('CGPA: 10');
ELSIF PERCEN <90 AND PERCEN >=80 THEN DBMS_OUTPUT.PUT_LINE('CGPA: 9');
ELSIF PERCEN <80 AND PERCEN >=70 THEN DBMS_OUTPUT.PUT_LINE('CGPA: 8');
ELSIF PERCEN <70 AND PERCEN >=60 THEN DBMS_OUTPUT.PUT_LINE('CGPA: 7');
ELSIF PERCEN <60 AND PERCEN >=50 THEN DBMS_OUTPUT.PUT_LINE('CGPA: 6');
ELSIF PERCEN <50 AND PERCEN >=45 THEN DBMS_OUTPUT.PUT_LINE('CGPA: 5');
ELSIF PERCEN <45 AND PERCEN >=40 THEN DBMS_OUTPUT.PUT_LINE('CGPA: 4');
ELSE DBMS_OUTPUT.PUT_LINE('CGPA: 0');
END IF;
END;