-- CREATE TABLE AUDIT_STU (OPER VARCHAR(10),RNO VARCHAR(10),NAME VARCHAR(20),DEPT VARCHAR(3) DEFAULT 'CSE', MOB_NO NUMBER(10), DOB DATE ,ADDRESS VARCHAR(15))
CREATE OR REPLACE TRIGGER AUDIT_STU_T 
    AFTER
    INSERT OR UPDATE OR DELETE ON STUDENT_20
    FOR EACH ROW
DECLARE
    OPER VARCHAR(10);
BEGIN
    IF INSERTING THEN 
        OPER := 'INSERT';
    ELSE 
        IF UPDATING THEN OPER:='UPDATE';
        
        ELSE OPER := 'DELETE';

        END IF;
    END IF;
    INSERT INTO AUDIT_STU VALUES(OPER,:OLD.RNO,:OLD.NAME,:OLD.DEPT,:OLD.MOB_NO,:OLD.DOB,:OLD.ADDRESS,SYSTIMESTAMP);

END;

