CREATE OR REPLACE TRIGGER UPPERCASE 
    BEFORE
    INSERT OR UPDATE OF NAME ON STUDENT_20
    FOR EACH ROW
BEGIN
    :NEW.NAME := UPPER(:NEW.NAME);
    DBMS_OUTPUT.PUT_LINE('CAPITALIZED NAME '|| :NEW.NAME);
END;