CREATE OR REPLACE FUNCTION area_circ_func (RADIUS NUMBER, INP NUMBER) RETURN NUMBER
IS
PI NUMBER(3,2):=3.14;
BEGIN

CASE INP
    WHEN 1 THEN RETURN ((2*PI)*(RADIUS));
    WHEN 2 THEN RETURN (PI*(RADIUS**2));
    ELSE RETURN NULL;
    END CASE;

END;