CREATE OR REPLACE FUNCTION FACTO_FUNC (INP NUMBER) RETURN NUMBER AS
    FAC NUMBER;
    I NUMBER;
BEGIN
    FAC := 1;
    FOR I IN 1 .. INP
    LOOP
        FAC := FAC * I;
    END LOOP;
    RETURN FAC;
END;