CREATE OR REPLACE PACKAGE EMPLOYEE_20_PACK
AS
FUNCTION EMP_HIRE(EMP_ID EMPLOYEE_20.EMP_ID%TYPE,
                EMP_NAME EMPLOYEE_20.EMP_NAME%TYPE,
                JOB EMPLOYEE_20.JOB%TYPE,
                SALARY EMPLOYEE_20.SALARY%TYPE,
                MANAGERID EMPLOYEE_20.MANAGERID%TYPE,
                DEPT_NO EMPLOYEE_20.DEPT_NO%TYPE)
                RETURN EMPLOYEE_20.EMP_ID%TYPE;
FUNCTION EMP_INC(EMP_ID EMPLOYEE_20.EMP_ID%TYPE,
                PERC NUMBER DEFAULT 5)
                RETURN EMPLOYEE_20.SALARY%TYPE;
PROCEDURE EMP_FIRE(EMP_ID EMPLOYEE_20.EMP_ID%TYPE);
END;