CREATE OR REPLACE PROCEDURE CALC (NUM_1 NUMBER,NUM_2 NUMBER,INP NUMBER)
AS
BEGIN
    CASE INP
        WHEN 1 THEN DBMS_OUTPUT.PUT_LINE('Addition: '|| (NUM_1+NUM_2));
        WHEN 2 THEN DBMS_OUTPUT.PUT_LINE('Subtraction: '|| (NUM_1-NUM_2));
        WHEN 3 THEN DBMS_OUTPUT.PUT_LINE('Multiplication: '|| (NUM_1*NUM_2));
        WHEN 4 THEN DBMS_OUTPUT.PUT_LINE('Division: '|| (NUM_1/NUM_2));
    END CASE;
END CALC;